#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

zstyle ':prezto:module:editor' key-bindings 'vi'
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export WORDCHARS=''  # make it stop at punctuation
unsetopt SHARE_HISTORY

for keymap in 'emacs' 'viins' 'vicmd'; do
    # [Ctrl-RightArrow] - move forward one word
    bindkey -M $keymap '^[[1;5C' forward-word
    # [Ctrl-LeftArrow] - move backward one word
    bindkey -M $keymap '^[[1;5D' backward-word
done

unset keymap

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/miki/google-cloud-sdk/path.zsh.inc' ]; then source '/home/miki/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/miki/google-cloud-sdk/completion.zsh.inc' ]; then source '/home/miki/google-cloud-sdk/completion.zsh.inc'; fi

# added by pipsi (https://github.com/mitsuhiko/pipsi)
export PATH="/home/miki/.local/bin:$PATH"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
