alias la='ls -a'
alias grep='grep --color=always'
alias less='less -R'
alias tree='tree -C'
alias pacman='pacaur'
alias upd='sudo pacman -Syy && sudo pacman -Syu'
alias orph='sudo pacman -R $(pacman -Qtdq)'
alias cacheclean='sudo pkgcacheclean -v 1'
alias dg='python -m dg'
alias und='underscore print --color'
alias hlint='hlint -c'
alias ccat='~/exp/bin/pygmentize -O style=fruity -f256 -g'
alias exe='exercism'
alias matlab='~/MATLAB2016a/bin/matlab -nodisplay -nosplash -nodesktop'
